"""added is_active flag on groups table

Revision ID: 2107f911e5e3
Revises: 291eb99a0321
Create Date: 2025-05-30 10:24:52.384060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2107f911e5e3'
down_revision = '291eb99a0321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telegram_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telegram_groups', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
