"""Initial migration

Revision ID: 291eb99a0321
Revises: 
Create Date: 2025-05-30 08:59:50.104567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '291eb99a0321'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telegram_user_id', sa.String(length=100), nullable=True),
    sa.Column('telegram_username', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telegram_user_id')
    )
    op.create_table('telegram_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_group_id', sa.String(length=100), nullable=False),
    sa.Column('telegram_group_name', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id'),
    sa.UniqueConstraint('telegram_group_id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('telegram_group_id', sa.Integer(), nullable=False),
    sa.Column('invite_link_token', sa.String(length=255), nullable=True),
    sa.Column('invite_link_url', sa.String(length=512), nullable=True),
    sa.Column('invite_link_expires_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_starts_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['telegram_group_id'], ['telegram_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_link_token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    op.drop_table('telegram_groups')
    op.drop_table('users')
    op.drop_table('products')
    # ### end Alembic commands ###
